---
title: "Datos"
editor: visual
---

## Grupos de interés organizaciones de movimientos sociales

La muestra seleccionada contiene 140 organizaciones de grupos de interés de ámbito nacional en 14 áreas temáticas. Estas organizaciones han sido identificadas como las más activas en las arenas parlamentaria y gubernamental en España de acuerdo con los registros públicos durante las dos últimas décadas.

Estas organizaciones fueron clasificadas en cinco tipos (Asociaciones empresariales, ONG, Organizaciones profesionales, Organizaciones de interés especial y sindicatos) siguiendo trabajos previos sobre grupos de interés y partidos.

```{r}

library(dplyr)
library(kableExtra)

rrigo_igos_140 <- read.csv2("data/rrigo_igos_140.csv")

rrigo_igos_140 %>%
  knitr::kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


### Comunicados de Prensa

### Redes sociales
Los datos de las intervenciones públicas de los grupos de interés se extrajeron de los perfiles oficiales de Twitter.


WORKING DRAFT – 02-09-2022

***Resumen***

Interest group organisations express the concerns and demands of their constituents and their particular understandings of policy issues on a daily basis in the public domain. Some of these narratives forge policy definitions which are shared by political elites to different extents. This paper studies to what extent political parties share the policy narratives used by interest group organizations focusing on the spaces and contexts of policy definition. Data from press releases of the 15 most salient interest groups, unions, and social movement organizations and the five main Spanish-speaking parties in Spain between 2008 and 2021 provide empirical evidence for large-scale analysis of policy rhetoric. Results show that interactions between groups and parties in parliamentary and government venues as well as in street protest have a very limited effect in explaining the use of interest group rhetoric by parties. Semantic similarity varies in different contexts, by party ideology, government status, interest group type and issue salience. These findings have a normative significance in terms of the representation function of interest groups and speaks to the potential inequalities in access to the policy process. They also shed light on the processes of policy change through the formation of political ideas and policy definition.

*Palabras clave:* Interest groups, policy narratives, rhetorical influence, semantic similarity, computational linguistics, NLP, quantitative text analysis

## [Elite adoption of interest group narratives in the Covid-19 Pandemic: A computational linguistics approach](https://www.dropbox.com/s/okcxv6ekmg2e8ol/Elite%20adoption%20of%20interest%20group%20narratives_05072022.pdf?dl=0)

Camilo Cristancho

WORKING DRAFT – 05-07-2022

***Resumen***

Interest groups played a fundamental role in tackling the problems generated by the Covid-19 pandemic as they link multiple issues and social groups in an unprecedented social challenge. Numerous organizations expressed their concerns and the demands of their constituents thus forging the narratives that shaped the agenda for dealing with the problems derived by a global pandemic in various sectors. However, given the dynamics of attention inherent to the emergency situation and the variety of challenges, it is not easy to follow the diversity and complexity of multiple actors and issues and more importantly, to understand their potential influence on the policy process. Using data from press releases and tweets of the 150 most salient interest groups, unions and social movement organizations in Spain, this paper studies the extent in which their narratives are adopted by political parties. Computational linguistics techniques are used to extract narratives of interest group organizations and to measure the degree in which they are appropriated by representatives on social media and the parliamentary arena. The implications of the adoption of public narratives by elites are discussed in light of the agenda dynamics and policy process literatures.

*Palabras clave:* Interest groups; influence; Covid-19 pandemic; Computational linguistics


## [Semantic similarity as common ground understanding in policy actor networks]()

Camilo Cristancho


***Resumen***


*Palabras clave:* Interest groups; influence; semantic similarity; policy; negotiation

